version: '3'

tasks:
  dev:
    desc: Run the development server
    cmds:
      - npm run dev

  build:
    desc: Build the application
    cmds:
      - npm run build

  preview:
    desc: Preview the production build
    cmds:
      - npm run preview

  check:
    desc: Run type checking
    cmds:
      - npm run check

  install:
    desc: Install dependencies
    cmds:
      - npm install
