version: '3'

tasks:
  dev:
    desc: Run the development server
    cmds:
      - pnpm run dev

  build:
    desc: Build the application
    cmds:
      - pnpm run build

  preview:
    desc: Preview the production build
    cmds:
      - pnpm run preview

  check:
    desc: Run type checking
    cmds:
      - pnpm run check

  install:
    desc: Install dependencies
    cmds:
      - pnpm install
